# Generated by Django 6.0.2 on 2026-02-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="students",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
    ]
